### ISSUE TITLE
crashes in WSL 2

### ISSUE THREAD

**Issue by jazzdan** [KeliLanguage/vscode-lsp#4]
Repro steps:

1. `git clone https://github.com/jazzdan/keli-lsp-crash`
2. `code .`
3. Install keli extension
4. Observe that the language server crashes repeatedly with the message below

```
vents.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn keli EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn keli',
  path: 'keli',
  spawnargs: [ 'analyze', '_src/__temp__.keli' ]
}
[Info  - 12:34:34 PM] Connection to server got closed. Server will restart.
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn keli EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn keli',
  path: 'keli',
  spawnargs: [ 'analyze', '_src/__temp__.keli' ]
}
[Info  - 12:34:34 PM] Connection to server got closed. Server will restart.
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn keli EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn keli',
  path: 'keli',
  spawnargs: [ 'analyze', '_src/__temp__.keli' ]
}
[Info  - 12:34:34 PM] Connection to server got closed. Server will restart.
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn keli EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn keli',
  path: 'keli',
  spawnargs: [ 'analyze', '_src/__temp__.keli' ]
}
[Info  - 12:34:34 PM] Connection to server got closed. Server will restart.
events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: spawn keli EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn keli',
  path: 'keli',
  spawnargs: [ 'analyze', '_src/__temp__.keli' ]
}
[Error - 12:34:34 PM] Connection to server got closed. Server will not be restarted.
```

My environment:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

Running in WSL 2 on Windows 10 Version 2004 (OS Build 19041.450)

Let me know if you need any other info!

**Comment by wongjiahau** [comment]
@jazzdan Thanks for the report! But sorry I couldn't help with this problem currently as I don't have a Windows (I'm using Ubuntu or Mac) so it's quite hard for me to debug this error.

**Comment by wongjiahau** [comment]
Do you have the Keli binary installed in your WSL? 

Currently the Keli binary is not published anywhere, so you need to clone the Keli compiler repository and build the binary from source using Stack Haskell.

**Comment by jazzdan** [comment]
Hey @wongjiahau,

Thanks for the response! I do have it installed and on my PATH. I'm wondering if there's some mismatch between the PATH that my shell has in WSL2 and the PATH that vscode launches with when launched from WSL 2. I'll try to investigate more.

**Comment by wongjiahau** [comment]
I see. I suspect it might also be the fact that this VSCode extension is outdated. Anyway let me know again if I can help!
